### ISSUE TITLE
MSE Implementation wrong

### ISSUE THREAD

**Issue by nicolas-schreiber** [jancervenka/turbofan_failure#2]
Hi,

I was very surprised of the results you claimed in your Readme. A 3.54 MSE would be amazing in this field. Sadly, you made a mistake when implementing the MSE. You added a np,sqrt where it should not be.

You wrote:
```
def MSE(RUL_real, RUL_pred):
    d = RUL_pred - RUL_real
    return np.sqrt(np.sum(np.square(d))) / len(d)
```

However, it should be:
```
def MSE(RUL_real, RUL_pred):
    d = RUL_pred - RUL_real
    return np.sum(np.square(d)) / len(d)
```

Even with worse results, this is still interesting work

**Comment by jancervenka** [comment]
Hi and thank you! I got back to this dataset to try a new approach and I just noticed your issue. You're absolutely correct! The formula in the new version is corrected.
